### ISSUE TITLE
Possible to use an SSH key with passcode?

### ISSUE THREAD

**Issue by ngottlieb** [tedconf/ember-cli-front-end-builds#24]
I'm running into this error trying to deploy to a front_end_builds app:

```
Done uploading assets
error:0906A068:PEM routines:PEM_do_header:bad password read
Error: error:0906A068:PEM routines:PEM_do_header:bad password read
    at Error (native)
    at Sign.sign (crypto.js:327:26)
    at Class.module.exports.Task.extend.signDeploy (/home/nickg/projects/subtext-ui/node_modules/ember-cli-front-end-builds/lib/tasks/deploy-index.js:63:8)
    at Class.module.exports.Task.extend.notifyEndpoint (/home/nickg/projects/subtext-ui/node_modules/ember-cli-front-end-builds/lib/tasks/deploy-index.js:73:23)
    at /home/nickg/projects/subtext-ui/node_modules/ember-cli-front-end-builds/lib/tasks/deploy-index.js:114:27
    at Array.forEach (native)
    at Class.module.exports.Task.extend.run (/home/nickg/projects/subtext-ui/node_modules/ember-cli-front-end-builds/lib/tasks/deploy-index.js:113:15)
    at /home/nickg/projects/subtext-ui/node_modules/ember-cli-front-end-builds/lib/commands/deploy.js:51:32
    at lib$rsvp$$internal$$tryCatch (/home/nickg/projects/subtext-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/nickg/projects/subtext-ui/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
```

My interpretation of this is that it's because my ssh key has a passcode, and I don't see a way to configure ember-cli-front-end-builds to utilize a passcode or an SSH agent. Am I wrong about that / is it in the pipeline?

**Comment by jah2488** [comment]
@ngottlieb @iirving @jhirbour Any luck with this issue before I start working on a fix?

**Comment by iirving** [comment]
I removed the passcode from my ssh key :( Go for it!

**Comment by jhirbour** [comment]
I haven't worked on a fix yet. I was able to get my deploy working by making a seperate key (with no pass phrase) for deployments.

**Comment by jah2488** [comment]
@jhirbour That was the route I was going to go as it seemed like less friction then trying to fork the repo and make needed changes.
